# black
export CYBERPUNK_COLOR_BLACK_1="#000000"
export CYBERPUNK_COLOR_BLACK_2="#777777"

# red
export CYBERPUNK_COLOR_RED_1="#FF0055"
export CYBERPUNK_COLOR_RED_2="#FF4081"

# green
export CYBERPUNK_COLOR_GREEN_1="#009550"
export CYBERPUNK_COLOR_GREEN_2="#00FF9C"

# yellow
export CYBERPUNK_COLOR_YELLOW_1="#F4EF00"
export CYBERPUNK_COLOR_YELLOW_2="#FFFC58"

# blue
export CYBERPUNK_COLOR_BLUE_1="#6766B3"
export CYBERPUNK_COLOR_BLUE_2="#76C1FF"

# magenta
export CYBERPUNK_COLOR_MAGENTA_1="#D57BFF"
export CYBERPUNK_COLOR_MAGENTA_2="#C592FF"

# cyan
export CYBERPUNK_COLOR_CYAN_1="#0DCDCD"
export CYBERPUNK_COLOR_CYAN_2="#00FFC8"

# white
export CYBERPUNK_COLOR_WHITE_1="#EEFFFF"
export CYBERPUNK_COLOR_WHITE_2="#FFFFFF"
